# **Creating Arrays in Numpy**

In [3]:
# import numpy library
import numpy as np

In [11]:
# create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
# create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)
# create a 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# create zeros array
zeros_arr = np.zeros((2,3))
print("Zeros Array:\n", zeros_arr)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# create ones array
ones_arr = np.ones((3, 4))
print("Ones Array:\n", ones_arr)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# create full array
full_arr = np.full((2, 3), 7) # fill with element 7
print("Full Array:\n", full_arr)

Full Array:
 [[7 7 7]
 [7 7 7]]


In [19]:
# creat range of array with step size
range_arr = np.arange(5, 15, 3)# start at 5, end before 15, step size 3
print("Range Array:", range_arr)

Range Array: [ 5  8 11 14]


In [20]:
# create linearly spaced array
linspace_arr = np.linspace(0, 1, 5) # start at 0, end at 1, total 5 elements
print("Linspace Array:", linspace_arr)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [21]:
# create identity matrix
indentity_arr = np.eye(3) # 3x3 identity matrix
print("Identity Matrix:\n", indentity_arr)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# create diagonal array
diag_arr = np.diag([1, 2, 3]) # create diagonal array with elements 1, 2, 3
print("Diagonal Array:\n", diag_arr)

Diagonal Array:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [23]:
# create array with type float
float_arr = np.array([1, 2, 3], dtype=float)
print("Float Array:", float_arr)

Float Array: [1. 2. 3.]


In [24]:
# array with type int
int_arr = np.array([1.5, 2.5, 3.5], dtype=int)
print("Integer Array:", int_arr)

Integer Array: [1 2 3]
