# **Numpy Indexing, Slicing & Strides**

In [1]:
# import numpy library
import numpy as np

In [10]:
# 2-D array of shape (3, 3)\
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
    
])

In [11]:
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print(arr.ndim) # number of dimensions

2


In [13]:
# indexing of 2-D array
print(arr[0, 1]) # element at row 0 and column 1

20


In [15]:
print(arr[2,2]) # element at row 2 and column 2

90


In [16]:
print(arr[-1, -1]) # element at last row and last column

90


In [17]:
print(arr[-1, -2]) # element at last row and second last column

80


In [18]:
print(arr[-3,-3]) # element at first row and first column

10


In [19]:
# General form of indexing: arr[start : stop : step]
print(arr[0:2, 0:2]) # subarray of first 2 rows and first 2 columns

[[10 20]
 [40 50]]


In [21]:
print(arr[0:2, 1:3]) # subarray of first 2 rows and last 2 columns

[[20 30]
 [50 60]]


In [22]:
print(arr[::2, ::2]) # subarray of every second row and every second column

[[10 30]
 [70 90]]


In [28]:
slice_arr = arr[0, :2] # view not copy
slice_arr[0] = 999
print(arr[0]) # original array is modified due to view

[999  20  30]


In [ ]:
copy_arr = arr[1].copy() # copy of second row
copy_arr[0] = 888 # modifying copy does not affect original array
print(copy_arr) # modified copy

[888  50  60]


In [33]:
print(arr)

[[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]
